SELECT DENSE_RANK() OVER(PARTITION BY WRITER_ID ORDER BY HIT), ID, TITLE, WRITER_ID, REGDATE, HIT
FROM NOTICE 
ORDER BY HIT;  


-- SUBQUERY
SELECT * FROM MEMBER WHERE ROWNUM BETWEEN 1 AND 10;

SELECT * 
FROM NOTICE
ORDER BY REGDATE DESC
WHERE ROWNUM BETWEEN 1 AND 5;


SELECT * FROM (SELECT * FROM MEMBER ORDER BY REGDATE DESC)
WHERE ROWNUM BETWEEN 1 AND 10;


SELECT * FROM MEMBER
WHERE AGE >= (SELECT AVG(AGE) FROM MEMBER);


-- JOIN
SELECT *
FROM MEMBER INNER JOIN NOTICE ON MEMBER.ID = NOTICE.WRITER.ID;

