SELECT * FROM NOTICE MEMBER JOIN MEMBER M ON N.WRITER_ID = M.ID;

SELECT * FROM NOTICE N LEFT OUTER JOIN MEMBER M ON N.WRITER_ID = M.ID;




-- inner join
SELECT NOTICE.ID, NOTICE.NAME, MEMBER.NAME FROM 
MEMBER
INNER JOIN NOTICE ON MEMBER.ID = NOTICE.ID;


-- OUTER JOIN
SELECT M.ID, M.NAME, COUNT(N.ID) FROM
MEMBER M INNER JOIN NOTICE N
ON M.ID = N.WRTIER_ID
GROUP BY M.ID, M.NAME;



SELECT M.ID, M.NAME, COUNT(N.ID) FROM
MEMBER M LEFT OUTER JOIN NOTICE N
ON M.ID = N.WRTIER_ID
GROUP BY M.ID, M.NAME;



-- SELF JOIN
