SELECT SUBSTR('HELLO', 1, 3) FROM DUAL;
SELECT SUBSTR('HELLO', 3) FROM DUAL;
SELECT SUBSTRB('HELLO', 3) FROM DUAL;

SELECT NAME, BIRTHDAY FROM MEMBERS;
SELECT NAME, SUBSTR(BIRTHDAY, 6, 2) FROM MEMBERS;
SELECT SUBSTR(NAME, 4) FROM MEMBERS;

-- 회원 중에서 전화번호가 011으로 시작하는 회원의 모든 정보를 출력하시오.
SELECT * FROM MEMBERS WHERE SUBSTR(PHONE, 1, 3) = '011';

SELECT * FROM MEMBERS WHERE PHONE IS NULL AND SUBSTR(BIRTHDAY, 6, 2) IN ('07', '08', '09');
UPDATE MEMBERS SET BIRTHDAY='1999-09-30' WHERE MID='NEWLEC';

-- we -> you
SELECT REPLACE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL;
-- w->y e->o
SELECT TRANSLATE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL;