SELECT SYSDATE, CURRENT_DATE, SYSTIMESTAMP, CURRENT_TIMESTAMP FROM DUAL;

ALTER SESSION SET IME_ZONE = '-1:0';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT EXTRACT(YEAR FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(MONTH FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(DAY FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(MINUTE FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(SECOND FORM SYSDATE) FROM DAUL;

SELECT ADD_MONTHS(SYSDATE, 1) FROM DAUL;
SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2013-12-25')) FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '≈‰ø‰¿œ') FROM DUAL;

SELECT ROUND(SYSDATE, 'CC'), TRUNC(SYSDATE, 'CC') FROM DUAL;
SELECT ROUND(SYSDATE, 'YEAR'), TRUNC(SYSDATE, 'YEAR') FROM DUAL;
SELECT ROUND(SYSDATE, 'Q'), TRUNC(SYSDATE, 'Q') FROM DUAL;
SELECT ROUND(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE, 'W'), TRUNC(SYSDATE, 'W') FROM DUAL;
SELECT ROUND(SYSDATE, 'DAY'), TRUNC(SYSDATE, 'DAY') FROM DUAL;
SELECT ROUND(SYSDATE, 'D'), TRUNC(SYSDATE, 'D') FROM DUAL;
SELECT ROUND(SYSDATE, 'HH'), TRUNC(SYSDATE, 'HH') FROM DUAL;
SELECT ROUND(SYSDATE, 'MI'), TRUNC(SYSDATE, 'MI') FROM DUAL;

