-- old join
SELECT N.ID,N.TITLE,M.NAME
FROM MEMBER M, NOTICE N
WHERE M.ID = N.WRITER_ID;

SELECT N.*, M.NAME WRITER_NAME
FROM NOTICE N JOIN MEMBER M ON M.ID = N.WRITER_ID;

SELECT N.*, M.NAME WRITER_NAME
FROM NOTICE N, MEMBER M WHERE M.ID = N.WRITER_ID;


-- ANSI OUTER JOIN
SELECT N.*, M.NAME WRITER_NAME
FROM NOTICE N LEFT OUTER JOIN MEMBER M
ON M.ID = N.WRITER_ID;

SELET N.*, M.NAME WRITER_NAME
FROM NOTICE N, MEMBER M
WHERE N.WRITER_ID = M.ID(+);


-- ANSI CROSS JOIN
SELECT N.*, M.NAME WRITER_NAME
FROM MEMBER M CROSS JOIN NOTICE N;