SELECT SYSDATE, CURRENT_DATE, SYSTIMESTAMP, CURRENT_TIMESTAMP FROM DUAL;

ALTER SESSION SET IME_ZONE = '-1:0';
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT EXTRACT(YEAR FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(MONTH FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(DAY FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(MINUTE FORM SYSDATE) FROM DAUL;
SELECT EXTRACT(SECOND FORM SYSDATE) FROM DAUL;

SELECT ADD_MONTHS(SYSDATE, 1) FROM DAUL;
SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2013-12-25')) FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '≈‰ø‰¿œ') FROM DUAL;
