-- 20210930
CREATE TABLE MEMBER
(
    ID       VARCHAR2(50),
    PWD      NVARCHAR2(50),
    NAME     NVARCHAR2(50),
    GENDER   NCHAR(2), -- 남성, 여성
    AGE      NUMBER(3),
    BIRTHDAY CHAR(50),
    PHONE    CHAR(50),
    REGDATE  DATE
);

INSERT INTO MEMBER (GENDER) VALUES('남성');

SELECT LENGTHB(GENDER) FROM MEMBER;

DROP TABLE MEMBER;

SELECT LENGTHB('ab') FROM DUAL;
SELECT LENGTHB('한글') FROM DUAL;

-- 20211002
ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);
ALTER TABLE MEMBER DROP COLUMN AGE;
ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);